### PR TITLE
fix(web): resolve dashboard issue URLs from tracker

### LINKED ISSUE #1213: Dashboard issue link broken: issueUrl set to raw issueId instead of full URL
## Bug

When a session is spawned with `ao spawn <issue-number>`, the dashboard renders a broken link for the issue. Clicking it navigates to `/<number>` instead of the GitHub issue URL.

## Root Cause

In the session serialization function (`ao-web/.next/server/chunks/538.js`, function `cg`), `issueUrl` is set to the raw `issueId`:

```javascript
issueUrl: a.issueId   // "1" instead of "https://github.com/owner/repo/issues/1"
```

The GitHub tracker plugin already has the correct `issueUrl()` method:

```javascript
// ao-plugin-tracker-github/dist/index.js
issueUrl(identifier, project) {
    const num = identifier.replace(/^#/, "");
    return `https://github.com/${project.repo}/issues/${num}`;
}
```

But it is never called during serialization. The enrichment function correctly calls `tracker.issueLabel()` and `tracker.getIssue()`, but `issueUrl` itself is not enriched — it is passed through as-is from `issueId`.

## Expected

`issueUrl` should be computed via `tracker.issueUrl(issueId, project)` before being sent to the frontend.

## Reproduction

```bash
ao start https://github.com/<owner>/<repo>
ao spawn 1
# Open dashboard -> session card shows issue link -> link href is "1" instead of full URL
```

## API response showing the bug

```json
{
  "id": "hom-1",
  "issueId": "1",
  "issueUrl": "1",
  "issueLabel": "#1",
  "issueTitle": "Create README for the repository"
}
```

`issueUrl` should be `https://github.com/owner/repo/issues/1`.

## Environment

- ao v0.2.2 (npm @composio/ao)
- macOS (Apple Silicon)
- GitHub tracker plugin

### PR DESCRIPTION
**Pull request by ChiragArora31**
## Summary
- resolve issue links from tracker metadata when sessions only store issue identifiers (for example `42`)
- keep existing absolute URLs unchanged and continue to enrich `issueLabel`/`issueTitle` from the resolved URL
- add regression coverage for identifier-only issue IDs in dashboard metadata enrichment

## Root cause
`sessionToDashboard()` treated `session.issueId` as a URL. For GitHub sessions spawned with an identifier, this produced invalid links like `/42` and broke downstream issue enrichment assumptions.

## What changed
- `sessionToDashboard()` now only initializes `issueUrl` when `issueId` is already an absolute URL.
- `enrichSessionIssue()` now resolves `dashboard.issueUrl` via `tracker.issueUrl()` using the available issue reference (`issueId` or existing `issueUrl`).
- metadata enrichment now runs issue enrichment when either `issueUrl` or `issueId` exists.
- tests updated to verify numeric issue identifiers are converted into valid tracker URLs.

## Why this approach
This keeps backward compatibility for sessions already storing full URLs while fixing identifier-only sessions at the existing enrichment boundary, avoiding schema changes or broader refactors.

## Testing
- `pnpm --filter @aoagents/ao-web test -- src/lib/__tests__/serialize.test.ts`

Closes #1213.

### CODE REVIEW

File: packages/web/src/lib/serialize.ts [hunk 1]
```diff
@@ -430,6 +439,19 @@ export function enrichSessionIssue(
   tracker: Tracker,
   project: ProjectConfig,
 ): void {
+  const issueReference = dashboard.issueId ?? dashboard.issueUrl;
+  if (!issueReference) return;
+
+  if (tracker.issueUrl) {
+    try {
+      dashboard.issueUrl = tracker.issueUrl(issueReference, project);
```
Comment (illegalcall) [inline packages/web/src/lib/serialize.ts]: **🔴 Bug 1 — Legacy URL-shaped `issueId` gets double-wrapped**

This calls `tracker.issueUrl(issueReference, project)` unconditionally, but real trackers don't normalize URL inputs — they blindly interpolate whatever string they're given:

- `packages/plugins/tracker-github/src/index.ts:167-170`
- `packages/plugins/tracker-gitlab/src/index.ts:80-85`
- `packages/plugins/tracker-linear/src/index.ts:317-324`

Sessions with `issueId=https://github.com/acme/repo/issues/99` (which the repo already persists — see `packages/core/src/__tests__/metadata.test.ts:44-64` and `packages/integration-tests/src/prompt-spawn.integration.test.ts:280-293`) now render a malformed link like:

```
https://github.com/<current-project-repo>/issues/https://github.com/acme/repo/issues/99
```

`issueTitle` then resolves to `#99` in the *current* project, not the original URL target. GitLab and Linear have the same bug.

**Fix:** guard the call on `!isAbsoluteUrl(issueReference)` and fall back to using `issueReference` directly when it's already a URL.

File: packages/web/src/lib/serialize.ts [hunk 2]
```diff
@@ -430,6 +439,19 @@ export function enrichSessionIssue(
...
+    } catch {
+      // Keep existing values if URL generation fails.
+    }
+  } else if (!dashboard.issueUrl) {
```
Comment (illegalcall) [inline packages/web/src/lib/serialize.ts]: **🟡 Bug 3 — `tracker.issueUrl()` return value trusted unconditionally**

`dashboard.issueUrl` is overwritten with whatever comes back. If a tracker throws, returns `""`, `null`, or a malformed string, the error is silently swallowed by this `catch {}` and the corrupted value renders straight into the dashboard's `href` attribute (`packages/web/src/components/SessionCard.tsx:347-364`).

**Fix:** validate that the generated URL parses via `isAbsoluteUrl()` before overwriting. Log on failure instead of silent catch.

File: packages/web/src/lib/serialize.ts [hunk 3]
```diff
@@ -535,7 +557,9 @@ function prepareSessionMetadataEnrichment(
 
   // Issue labels (synchronous string parsing, no API calls)
   projects.forEach((project, i) => {
-    if (!dashboardSessions[i].issueUrl || !project?.tracker?.plugin) return;
+    if ((!dashboardSessions[i].issueUrl && !dashboardSessions[i].issueId) || !project?.tracker?.plugin) {
```
Comment (illegalcall) [inline packages/web/src/lib/serialize.ts:582]: **🔴 Bug 2 — Free-text / unresolved `issueId` now produces fake clickable links**

This broadens the enrichment gate so any non-empty `issueId` triggers URL/label/title generation. But core intentionally allows sessions with unresolved or free-text `issueId` values (see `packages/core/src/__tests__/session-manager/spawn.test.ts:853-897`).

A session spawned with `issueId="fix login bug"` or an unresolved `INT-9999` now gets:
- A synthetic tracker URL rendered as a clickable `href` (`packages/web/src/components/SessionCard.tsx:347-364`)
- A synthetic label
- Repeated failing `tracker.getIssue()` API calls on every dashboard refresh (via `packages/web/src/app/api/sessions/route.ts` and `packages/web/src/app/api/sessions/[id]/route.ts`)

**Fix:** only enrich when the session has evidence of being tracker-resolvable (e.g., tracker returned a resolved `Issue` at spawn time), or validate that the generated URL is well-formed before assigning it.

File: packages/web/src/lib/__tests__/serialize.test.ts [hunk 4]
```diff
@@ -872,7 +872,11 @@ describe("enrichSessionsMetadata", () => {
         labels: [],
       }),
       isCompleted: vi.fn().mockResolvedValue(false),
-      issueUrl: vi.fn().mockReturnValue(`${urlBase}-default`),
+      issueUrl: vi.fn().mockImplementation((identifier: string) =>
+        identifier.startsWith("http://") || identifier.startsWith("https://")
+          ? identifier
+          : `${urlBase}-${identifier}`,
+      ),
```
Comment (illegalcall) [inline packages/web/src/lib/__tests__/serialize.test.ts]: **🟡 Issue 4 — Tests mask the main regression**

This mock special-cases absolute URLs and returns them unchanged. **No real tracker does this** — the GitHub/GitLab/Linear plugins all interpolate the identifier into a URL template without checking whether it's already a URL.

The suite therefore passes the exact full-URL case that production breaks, and has no coverage for the unresolved/free-text `issueId` path.

**Fix:** align the mock with real tracker behavior (blind interpolation), then add regression tests for:
- (a) URL-shaped `issueId` round-tripping unchanged
- (b) free-text `issueId` *not* producing a synthetic URL
- (c) tracker `issueUrl()` throwing

File: packages/web/src/lib/serialize.ts [hunk 5]
```diff
@@ -430,6 +439,19 @@ export function enrichSessionIssue(
   tracker: Tracker,
   project: ProjectConfig,
 ): void {
+  const issueReference = dashboard.issueId ?? dashboard.issueUrl;
```
Comment (illegalcall) [inline packages/web/src/lib/serialize.ts:444]: **Nit — JSDoc drift**

`enrichSessionIssue`'s JSDoc just above still says "Enrich a DashboardSession's issue label," but this block now also regenerates `issueUrl`. Worth updating the doc comment to match.

**Review by illegalcall — COMMENTED** [review]
## Review findings

Good catch on the pre-existing bug — the old `// issueId is actually the full URL` comment was wrong for identifier-only spawns like `ao spawn proj 42`. `isAbsoluteUrl` using the standard URL parser + `http:`/`https:` restriction safely rejects `javascript:` / `data:` / etc. Small, focused diff and a graceful fallback path when `tracker.issueUrl` isn't implemented.

That said, two regressions in the enrichment path break real session data, plus test mocks that mask the main one. Details inline.

File: packages/web/src/lib/serialize.ts (hunk 1 above)
Comment (ChiragArora31) [reply packages/web/src/lib/serialize.ts]: Nice catch. I now short-circuit URL-shaped references (`isAbsoluteUrl(issueReference)`) and skip `tracker.issueUrl()` for those, so legacy full URLs round-trip unchanged instead of being double-wrapped.

File: packages/web/src/lib/serialize.ts (hunk 2 above)
Comment (ChiragArora31) [reply packages/web/src/lib/serialize.ts]: Agreed — added strict validation before overwrite. We only assign when `tracker.issueUrl()` returns an absolute HTTP(S) URL, and now log failures/invalid outputs instead of silently swallowing them.

File: packages/web/src/lib/serialize.ts (hunk 3 above)
Comment (ChiragArora31) [reply packages/web/src/lib/serialize.ts:582]: Fixed this path in two parts: free-text `issueId` values (contains whitespace) no longer generate synthetic tracker URLs, and failed `getIssue()` lookups are miss-cached briefly so we do not repeatedly hammer tracker APIs on each refresh.

File: packages/web/src/lib/__tests__/serialize.test.ts (hunk 4 above)
Comment (ChiragArora31) [reply packages/web/src/lib/__tests__/serialize.test.ts]: Updated tests to match real tracker behavior (blind interpolation), and added regressions for: (a) URL-shaped `issueId` round-tripping unchanged, (b) free-text `issueId` not producing a clickable URL, and (c) `tracker.issueUrl()` throwing.

File: packages/web/src/lib/serialize.ts (hunk 5 above)
Comment (ChiragArora31) [reply packages/web/src/lib/serialize.ts:444]: Good call — updated the JSDoc to reflect that `enrichSessionIssue` now enriches both URL and label, not label only.

**Comment by ChiragArora31** [comment]
@illegalcall issues resolved, kindly review it

**Review by illegalcall — APPROVED** [review]
