### PR TITLE
fix(cli): make ao start URL cloning interactive to avoid SSH prompt hang

### LINKED ISSUE #1256: fix(ao start): URL clone can hang on SSH host-key prompt (non-interactive exec)
## Summary
Running `ao start <github-url>` can **hang indefinitely** during the clone step when Git/SSH prompts for interactive input (most commonly **first-time host key verification** for `github.com`). Because the clone is executed in a non-interactive way, the prompt cannot be answered, and the process does not error/return — so `ao start` never proceeds to its intended HTTPS fallback.

Image

## Environment
- CLI: `ao start <url>`
- Scenario: machine/user without an existing `~/.ssh/known_hosts` entry for `github.com` (or any case where `ssh` prompts)

## Steps to reproduce
1. Ensure `github.com` is not present in `~/.ssh/known_hosts` (fresh machine/user profile, or remove that entry).
2. Run:

```bash
ao start https://github.com/<owner>/<repo>.git
```

3. Observe output similar to:

```text
The authenticity of host 'github.com (..)' can't be established.
ED25519 key fingerprint is ...
Are you sure you want to continue connecting (yes/no/[fingerprint])?
```

## Actual behavior
- The process becomes **stuck at the SSH prompt** and does not accept `yes/no` input.
- `ao start` does not exit, and the clone flow does not advance to the next fallback.

## Expected behavior
- If a command requires interactivity (host-key prompt, credentials, etc.), `ao start` should **inherit the user’s TTY** so input can be provided.
- If the SSH clone fails, `ao start` should **fall back** to the next strategy (e.g. HTTPS) rather than hanging indefinitely.

## Technical root cause
The URL start path performs cloning in multiple strategies (gh -> git+ssh -> git+https). The SSH strategy can invoke `ssh` which prints a prompt and waits for stdin.

When the clone is executed via a non-interactive child-process invocation (no TTY/stdin forwarding), the underlying `ssh` prompt cannot be answered. In this state:
- the child process waits forever for input,
- no exception is thrown,
- and the orchestrator cannot continue to the fallback stage.

## Proposed fix
Run clone/install subprocesses using `spawn(..., { stdio: 'inherit' })` (or an equivalent helper) so interactive prompts can be answered and the process can either complete or fail deterministically.

## Related PR
Fix implemented in PR #1255.

### PR DESCRIPTION
**Pull request by rogdex24**
Fixes #1256

## Problem
When running `ao start <github-url>`, the URL clone flow tries multiple strategies (gh -> git+ssh -> git+https). The git+ssh path can trigger an interactive SSH prompt (most commonly first-time `github.com` host-key verification: "Are you sure you want to continue connecting (yes/no/[fingerprint])?").

Because the clone command was executed in a non-interactive way (stdin/TTY not forwarded), the prompt could not be answered. The process would block indefinitely, meaning:
- `ao start` appeared stuck
- the clone step never errored
- the flow never reached the intended HTTPS fallback

## Solution
- Run clone/install subprocesses with TTY forwarding (`spawn(..., { stdio: \"inherit\" })`) so prompts accept input and failures are deterministic.
- Extend `runInteractiveCommand(cmd, args)` with an optional options bag (`cwd`, `env`, `action`, `installHints`) and reuse it across these flows.
- Remove the redundant interactive spawn helper to prevent drift.

works now as it accepts input and fallbacks if it fails
image

## Behavior change
- `ao start <url>` no longer hangs on SSH prompts; users can respond to prompts, and if SSH clone fails, the code can proceed to the next fallback strategy.

## Test plan
- On a machine/user without `github.com` in `~/.ssh/known_hosts`, run `ao start <github-url>` and verify the `yes/no` prompt accepts input and cloning completes (or fails and falls back deterministically).
- Verify installer prompts still work and error messages remain well-formatted.

### CODE REVIEW

**Comment by illegalcall** [comment]
Hey @rogdex24 Can you please resolve the conflict here?

**Comment by rogdex24** [comment]
> Hey @rogdex24 Can you please resolve the conflict here?

sure

**Comment by rogdex24** [comment]
@illegalcall please check

File: packages/cli/src/commands/start.ts [hunk 1]
```diff
@@ -460,27 +479,35 @@ async function cloneRepo(parsed: ParsedRepoUrl, targetDir: string, cwd: string):
...
       }
     }
   }
 
-  // 2. Try git clone with SSH URL (works with SSH keys for private repos)
+  // 2. Try git clone with SSH URL (works for SSH keys, may prompt for host key)
   const sshUrl = `git@${parsed.host}:${parsed.ownerRepo}.git`;
   try {
-    await exec("git", ["clone", "--depth", "1", sshUrl, targetDir], { cwd });
+    await runInteractiveCommand("git", ["clone", "--depth", "1", sshUrl, targetDir], {
```
Comment (illegalcall) [inline packages/cli/src/commands/start.ts:497]: SSH clone here can hang indefinitely (not fast-fail) when the PTY has no human at it — common in AO since agents run `ao start` inside their own tmux session. SSH sees a real TTY and prompts for host-key/passphrase; nobody types; the `await` never returns; the HTTPS fallback at L507 is unreachable.

Suggest passing `GIT_TERMINAL_PROMPT: "0"` and `GIT_SSH_COMMAND: "ssh -o BatchMode=yes -o StrictHostKeyChecking=accept-new"` via `options.env` so the prompt fast-fails into HTTPS instead.

Comment (rogdex24) [reply packages/cli/src/commands/start.ts:497]: Correct me if I'm wrong 

But that's what the interactive command is for, even for the first time setup using ao start it is going to indefinitely wait if user doesn't give input for plugin choice etc. 

It's how the git clone command functions and we are extending it. 

Are you suggesting we just force this to work without ssh key else just fail ?

Comment (illegalcall) [reply packages/cli/src/commands/start.ts:497]: Youre right. Should have reviewed it myself

**Review by illegalcall — APPROVED** [review]
