### PR TITLE
fix(core): preserve reaction tracker across status oscillation

### LINKED ISSUE #1409: Stale reaction dispatch: CI failure and merge conflict messages injected repeatedly despite PR being clean
## Bug

The lifecycle manager repeatedly injects "CI is failing on your PR" and "Your branch has merge conflicts" messages to agent sessions even when the associated PR has passing CI and no merge conflicts. The agent dismisses them as stale noise, but they keep coming.

**Discord thread:** https://discord.com/channels/1481732697225539674/1491735678156013588/1496203865740283987
**Reported by:** @prateek
**Analyzed against:** \`59f66f4\` (main)

## Screenshot

See Discord thread — screenshot shows 16+ repeated messages alternating between CI failure and merge conflict dispatches within a single agent session.

## Root Cause

**Status oscillation resets reaction trackers, bypassing retry limits.**

The reaction dispatch chain:

1. **\`checkSession()\`** (\`lifecycle-manager.ts:1634\`) runs \`determineStatus()\` which queries PR state via batch GraphQL enrichment.

2. When \`newStatus !== oldStatus\` (line 1682), the **old status's reaction tracker is cleared** (lines 1712-1718):
   \`\`\`ts
   const oldEventType = statusToEventType(undefined, oldStatus);
   if (oldEventType) {
     const oldReactionKey = eventToReactionKey(oldEventType);
     if (oldReactionKey) {
       clearReactionTracker(session.id, oldReactionKey);
     }
   }
   \`\`\`

3. The **new status's reaction fires** via \`executeReaction()\` (line 1733) — which creates a fresh tracker with \`attempts: 0\`.

4. The \`ci-failed\` reaction has \`retries: 2\`, so it should fire at most 3 times before escalating. But **every oscillation out of \`ci_failed\` clears the tracker, and every oscillation back creates a fresh one** — effectively resetting the retry budget.

**The oscillation trigger:** The \`resolvePREnrichmentDecision()\` path in \`determineStatus()\` (line 739-746) uses batch GraphQL data from \`prEnrichmentCache\`. When the ETag guard (\`shouldRefreshPREnrichment()\` in \`graphql-batch.ts:177\`) says "no changes detected", stale cached data is returned (line 895-916). If the cached data says \`ciStatus: "failing"\` or \`mergeable === "CONFLICTING"\` but the PR has since been fixed, the status incorrectly becomes \`ci_failed\` on every poll cycle — re-firing the reaction.

**Contributing factors:**
- \`statusToEventType()\` (line 139) only considers the **target** status, not the source. So \`working → ci_failed\` and \`pr_open → ci_failed\` both produce \`ci.failing\`.
- \`maybeDispatchCIFailureDetails()\` (line 1291) has fingerprint-based dedup, but the **transition reaction** at line 1733 is NOT fingerprint-gated — it fires the static message "CI is failing on your PR. Run gh pr checks..." every time the status transitions to \`ci_failed\`.
- \`maybeDispatchMergeConflicts()\` (line 1424) uses \`lastMergeConflictDispatched\` metadata for dedup, but stale cached \`hasConflicts: true\` from the ETag guard bypass prevents the "conflicts resolved" path (line 1512-1518) from clearing the flag.

## Fix

**Option A (recommended) — Don't clear reaction tracker for the old status on exit.** The tracker should only be cleared when the condition that triggered the reaction is genuinely resolved (CI goes from failing → passing via live check, conflicts confirmed resolved). Change lines 1712-1718 to only clear trackers for states that were verified as resolved.

**Option B — Add a "recently dispatched" timestamp guard.** Before firing \`executeReaction()\` at line 1733, check if the same reaction was dispatched within the last N seconds and skip if so.

**Option C — Live verification before reaction dispatch.** When the batch cache says CI is failing, make a live \`scm.getCISummary()\` call to confirm before injecting the message.

## Impact

- Agents waste tokens repeatedly dismissing false CI/merge conflict alerts
- Agents may attempt unnecessary fixes (rebase, CI check) on clean PRs
- Creates noise in the agent context window, degrading task performance
- Burns GitHub API rate limit on redundant gh pr checks calls from the agent side

### PR DESCRIPTION
**Pull request by iamasx**
Closes #1409

## Summary

The lifecycle manager's reaction system has a retry + escalate mechanism: when CI fails, it sends a message to the agent, and after N retries (`retries: 2` = 3 attempts), escalates to a human. But the retry budget was resetting on every status oscillation, causing infinite message spam and preventing escalation.

**Three root causes fixed:**

1. **Reaction tracker cleared unconditionally on status exit** (`lifecycle-manager.ts:1878-1885`). Every transition away from `ci_failed` deleted the tracker. When CI failed again, a fresh tracker was created with `attempts: 0`. The retry budget never exhausted.

2. **Merge conflict dispatch bypassed `executeReaction` entirely** (`lifecycle-manager.ts:1654-1676`). `maybeDispatchMergeConflicts()` called `sessionManager.send()` directly, so the `escalateAfter: "15m"` config for merge-conflicts was dead code — escalation could never trigger.

3. **Merge conflict tracker cleared on resolve** (`lifecycle-manager.ts:1680`). When conflicts resolved, both the reaction tracker and dedup flag were cleared. When conflicts recurred, the escalation budget started from zero.

### Change 1: Persistent reaction keys

Added `PERSISTENT_REACTION_KEYS = new Set(["ci-failed", "merge-conflicts"])`. These keys represent conditions that can oscillate (CI failing→pending→failing, conflicts resolving→recurring). Their trackers survive status exit so the escalation budget accumulates across oscillations.

At the status-exit clear (line 1883), persistent keys are now excluded:
```typescript
if (oldReactionKey && !PERSISTENT_REACTION_KEYS.has(oldReactionKey)) {
  clearReactionTracker(session.id, oldReactionKey);
}
```

### Change 2: Route merge conflicts through `executeReaction`

Replaced direct `sessionManager.send()` / `notifyHuman()` calls in `maybeDispatchMergeConflicts()` with a call to `executeReaction()`. This enables the existing `escalateAfter: "15m"` config that was previously ignored. Dynamic base branch messages are built before the call via an enriched config.

### Change 3: Preserve merge-conflicts tracker on resolve

When conflicts resolve, only the dedup flag (`lastMergeConflictDispatched`) is cleared — allowing re-notification if conflicts recur. The reaction tracker is preserved so the escalation budget continues counting. Terminal-state clearing (PR closed/merged) remains unchanged.

### Behavior after fix

**CI failure oscillation:**
```
Poll 1: CI failing  → send to agent       (attempts: 1)
Poll 2: CI pending  → tracker PRESERVED
Poll 3: CI failing  → send to agent       (attempts: 2)
Poll 4: CI pending  → tracker PRESERVED
Poll 5: CI failing  → attempts 3 > retries 2 → ESCALATE TO HUMAN
```

**Merge conflict oscillation:**
```
Conflict 1: send to agent (attempts: 1, firstTriggered = T)
Resolved:   dedup flag cleared, tracker preserved
Conflict 2: send to agent (attempts: 2)
Resolved:   dedup flag cleared, tracker preserved
Conflict 3: if T + 15min elapsed → ESCALATE TO HUMAN
```

## Test plan

- [x] **CI failure oscillation test**: Simulates 3 oscillations (ci_failed → pr_open → ci_failed). Verifies agent receives messages on attempts 1-2, then human is notified via escalation on attempt 3.
- [x] **Merge conflict time-based escalation test**: Simulates conflict → resolve → recur with `vi.useFakeTimers()`. Verifies escalation triggers after the `escalateAfter` window.
- [x] **Non-persistent keys test**: Verifies `changes-requested` tracker still clears on status exit (only persistent keys are protected).
- [x] All 917 existing tests pass
- [x] Full typecheck passes across all packages

### CODE REVIEW

File: packages/core/src/lifecycle-manager.ts [hunk 1]
```diff
@@ -394,6 +394,11 @@ export function createLifecycleManager(deps: LifecycleManagerDeps): LifecycleMan
 
   const states = new Map<SessionId, SessionStatus>();
   const reactionTrackers = new Map<string, ReactionTracker>(); // "sessionId:reactionKey"
+
+  /** Reaction keys for conditions that can oscillate (e.g. CI failing→pending→failing).
+   *  Their trackers survive status exit so the escalation budget accumulates
+   *  across oscillations instead of resetting to zero each time. */
+  const PERSISTENT_REACTION_KEYS = new Set(["ci-failed", "merge-conflicts"]);
```
[the remark this answers is not in the document]
Comment (iamasx) [reply packages/core/src/lifecycle-manager.ts]: Fixed in 8a64a5a2 — hoisted PERSISTENT_REACTION_KEYS to module scope alongside the other module-level constants.

File: packages/core/src/lifecycle-manager.ts [hunk 2]
```diff
@@ -1652,32 +1657,32 @@ export function createLifecycleManager(deps: LifecycleManagerDeps): LifecycleMan
...
-            await sessionManager.send(session.id, message);
-          } else {
-            const event = createEvent("merge.conflicts", {
-              sessionId: session.id,
-              projectId: session.projectId,
-              message: `${session.id}: PR has merge conflicts`,
-            });
-            await notifyHuman(event, reactionConfig.priority ?? "warning");
+            enrichedConfig.message = `Your PR branch${behindNote} has merge conflicts with ${baseBranch}. Rebase your branch on ${baseBranch}, resolve the conflicts, and push. You should not need to call gh for merge status unless you need additional context — this information is current.`;
           }
```
[the remark this answers is not in the document]
Comment (iamasx) [reply packages/core/src/lifecycle-manager.ts]: Good catch. The default config for `merge-conflicts` uses `action: "send-to-agent"` (not `"notify"`), so this doesn't affect the default path — priority is only relevant for escalation there, which correctly defaults to `"urgent"`.

For users who override to `action: "notify"`, the old direct-dispatch code defaulted to `"warning"` while `executeReaction`'s notify path defaults to `"info"`. Rather than setting `priority: "warning"` on the enriched config (which would also override the escalation path's `"urgent"` default), I've added a comment documenting that `action: "notify"` users should set `priority: "warning"` explicitly in their config if they want the previous behavior.

Addressed in 8a64a5a2.

**Comment by iamasx** [comment]
## High-Level Summary

The reaction system is designed to send messages to agents when problems occur (CI failing, merge conflicts), retry a few times, then escalate to a human if the agent can't fix it. The escalation was never triggering because the retry counter reset to zero every time the status briefly changed — e.g., CI goes `failing → pending → failing` each time the agent pushes a fix attempt.

**What this PR does:**

1. **Stops clearing retry counters for oscillating conditions.** CI failure and merge conflict trackers now survive status transitions. After 3 failed CI fix attempts (configurable via `retries`), the system escalates to a human instead of spamming the agent forever.

2. **Wires up merge conflict escalation.** The `escalateAfter: "15m"` config for merge conflicts was dead code — `maybeDispatchMergeConflicts` dispatched directly via `sessionManager.send()`, bypassing the retry/escalation system entirely. Now routed through `executeReaction` so time-based escalation actually works.

3. **Preserves existing behavior for non-oscillating reactions.** `changes-requested`, `pr-closed`, `agent-stuck`, etc. still clear their trackers on status exit — only `ci-failed` and `merge-conflicts` are protected.

**Scope:** 2 files changed — `lifecycle-manager.ts` (code) + `lifecycle-manager.test.ts` (3 new tests). All 917 existing tests pass.

File: packages/core/src/lifecycle-manager.ts [hunk 3]
```diff
@@ -92,6 +92,11 @@ function parseDuration(str: string): number {
   }
 }
 
+/** Reaction keys for conditions that can oscillate (e.g. CI failing→pending→failing).
+ *  Their trackers survive status exit so the escalation budget accumulates
+ *  across oscillations instead of resetting to zero each time. */
+const PERSISTENT_REACTION_KEYS = new Set(["ci-failed", "merge-conflicts"]);
```
Comment (illegalcall) [inline packages/core/src/lifecycle-manager.ts]: **Dead code: drop `"merge-conflicts"` here.** It's unreachable from the transition handler at line 1892 — `statusToEventType` (lines 224-) only emits status-derived event types (`ci.failing`, `review.changes_requested`, etc.) and never `merge.conflicts`. The actual mechanism preserving the merge-conflicts tracker across oscillation is the removal of `clearReactionTracker` at the resolved branch (line 1686-1690), not membership in this set.

Keeping it here is misleading — a future maintainer will think this set protects merge-conflicts when it's actually unrelated. illegalcall flagged this on the previous closed PR (#1479):
> Drop `"merge-conflicts"` from the set — `statusToEventType` (:139-167) never emits `merge.conflicts`, so `eventToReactionKey(oldEventType)` can't return `"merge-conflicts"`. Dead code.

File: packages/core/src/lifecycle-manager.ts [hunk 4]
```diff
@@ -1652,32 +1657,35 @@ export function createLifecycleManager(deps: LifecycleManagerDeps): LifecycleMan
...
-          });
+          const result = await executeReaction(
+            session.id,
+            session.projectId,
+            conflictReactionKey,
+            enrichedConfig,
+          );
+          if (result.success) {
+            updateSessionMetadata(session, {
+              lastMergeConflictDispatched: "true",
```
Comment (illegalcall) [inline packages/core/src/lifecycle-manager.ts:1705]: **Escalation success poisons the dedup flag (high impact).**

When `executeReaction` takes the escalation path (line 1195) — either because `attempts > retries` or `Date.now() - firstTriggered > escalateAfter` — it returns `{ success: true, action: "escalated" }`. This conditional fires unconditionally on `result.success`, so `lastMergeConflictDispatched: "true"` is written.

Next cycle hits the dedup early-return at line 1650 → no-op. Every subsequent resolve→recur cycle re-fires the **urgent** human notification while the agent stays silent. Worse than the original #1409 bug for the human (urgent pages instead of agent spam).

Fix:
```ts
if (result.success && result.action !== "escalated") {
  updateSessionMetadata(session, { lastMergeConflictDispatched: "true" });
}
```

Or alternatively: clear the tracker entirely on escalation, accepting the "human owns it now" semantic and stopping further escalations from this incident.

File: packages/core/src/lifecycle-manager.ts [hunk 5]
```diff
@@ -1652,32 +1657,35 @@ export function createLifecycleManager(deps: LifecycleManagerDeps): LifecycleMan
...
         } catch {
-          // Send failed — will retry on next poll cycle
+          // Dispatch failed — will retry on next poll cycle
         }
       }
     } else if (lastDispatched === "true") {
-      // Conflicts resolved — clear so we can re-dispatch if they recur
-      clearReactionTracker(session.id, conflictReactionKey);
+      // Conflicts resolved — clear dedup flag so we can re-dispatch if they recur,
+      // but preserve reaction tracker so escalation budget accumulates.
```
Comment (illegalcall) [inline packages/core/src/lifecycle-manager.ts]: **Permanent budget instead of incident budget.**

`executeReaction` sets `tracker.firstTriggered` once at creation (line ~967) and never resets it. Combined with this comment's intent — "preserve reaction tracker so escalation budget accumulates" — the tracker now lives for the entire session lifetime. With default `escalateAfter: "15m"`, once the original conflict is older than 15 minutes, every future conflict on the same session escalates immediately on first dispatch, bypassing the agent.

Long-lived PRs (open for days/weeks, conflicts resolved on day 1, new conflicts on day 30) never give the agent a fresh chance to fix it.

This is the inverse regression of the original bug: instead of "infinite spam, no escalation," you get "one escalation, then silence forever." Both extremes are wrong.

Fix options (pick one):
1. Reset the tracker after `hasConflicts` has been false for N consecutive polls (incident-resolved boundary).
2. Key the tracker on `session.pr.headSha` so a new commit gets a fresh budget.
3. Clear the tracker on escalation success, treating each escalation as terminal for the incident.

The new test at lines 2763+ asserts the buggy behavior as intended (`expect(send).not.toHaveBeenCalled()`). Add a counter-test: conflict resolved for >`escalateAfter`, then new conflict appears — agent should still be notified, not just escalation.

File: packages/core/src/lifecycle-manager.ts [hunk 6]
```diff
@@ -1652,32 +1657,35 @@ export function createLifecycleManager(deps: LifecycleManagerDeps): LifecycleMan
         (reactionConfig.auto !== false || reactionConfig.action === "notify")
       ) {
         try {
-          if (reactionConfig.action === "send-to-agent") {
+          // Build enriched config with dynamic base branch message.
+          // Note: executeReaction's notify path defaults to "info" priority (was "warning"
```
Comment (illegalcall) [inline packages/core/src/lifecycle-manager.ts]: **Code comment is documentation, not mitigation.**

The old direct-dispatch code defaulted `action: "notify"` merge-conflicts to `"warning"` priority. The new `executeReaction` notify case at line 1070 defaults to `"info"`. For users with config like:
```yaml
notificationRouting:
  warning: [slack]
  info: []  # or unset
```
and `merge-conflicts: { action: "notify" }` (no explicit priority), `notifyHuman` now iterates zero notifiers and returns silently. `executeReaction` still returns `success: true`, the dedup flag is set, the user never finds out.

Mitigation: override priority before calling executeReaction:
```ts
const enrichedConfig = {
  ...reactionConfig,
  priority: reactionConfig.priority ?? "warning",
};
```

The new test at line ~2240 masks this regression by routing both `warning` and `info` to `desktop`. Add a regression test where `info` routing is empty and verify the warning notifier still fires.

File: packages/core/src/lifecycle-manager.ts [hunk 7]
```diff
@@ -1875,11 +1883,13 @@ export function createLifecycleManager(deps: LifecycleManagerDeps): LifecycleMan
...
 
-      // Clear reaction trackers for the old status so retries reset on state changes
+      // Clear reaction trackers for the old status so retries reset on state changes.
+      // Persistent keys (ci-failed, merge-conflicts) are excluded — their trackers
+      // survive oscillation so the escalation budget accumulates across cycles.
       const oldEventType = statusToEventType(undefined, oldStatus);
       if (oldEventType) {
         const oldReactionKey = eventToReactionKey(oldEventType);
-        if (oldReactionKey) {
+        if (oldReactionKey && !PERSISTENT_REACTION_KEYS.has(oldReactionKey)) {
```
Comment (illegalcall) [inline packages/core/src/lifecycle-manager.ts:1942]: **Same permanent-budget problem applies to `ci-failed`.**

The gate correctly preserves the tracker across pr_open ↔ ci_failed oscillation (the #1409 fix). But it also preserves it across legitimate "CI failed → fixed → new push fails CI weeks later" cycles. A long-lived session that exhausted retries on day 1 will hit the escalation path for every future ci_failed entry on day 30, with the original `attempts` counter and original `firstTriggered` carried over.

Same shape as the merge-conflicts H2 issue at line 1688. Same fix family applies — needs an incident boundary:
- Reset the tracker when CI transitions to `passing` and stays there for a stable window, OR
- Key the tracker on `session.pr.headSha` so a new commit's failure starts fresh.

Without one of these, the fix replaces "infinite spam" with "agent silenced after one bad week."

**Review by illegalcall — CHANGES_REQUESTED** [review]
Three issues to fix before merge:

1. Escalation success poisons the merge-conflict dedup flag (line 1679) — every resolve→recur cycle re-fires urgent human pages while the agent goes silent.
2. No incident boundary on either persistent tracker (lines 1688, 1892) — long-lived sessions exhaust the budget once and escalate forever after.
3. Silent priority shift from `warning` to `info` for `action: "notify"` merge-conflicts (line 1661) — users with warning-only routing lose notifications.

Plus one cosmetic: `"merge-conflicts"` in `PERSISTENT_REACTION_KEYS` (line 98) is dead code — illegalcall called this out on the previous closed PR (#1479). Worth removing so the comment doesn't mislead future maintainers.

File: packages/core/src/lifecycle-manager.ts (hunk 3 above)
Comment (iamasx) [reply packages/core/src/lifecycle-manager.ts]: Fixed in a0aab2bc — removed `"merge-conflicts"` from `PERSISTENT_REACTION_KEYS`. Updated the comment to document that merge-conflict tracker lifecycle is managed in `maybeDispatchMergeConflicts`, not via the transition handler.

File: packages/core/src/lifecycle-manager.ts (hunk 4 above)
Comment (iamasx) [reply packages/core/src/lifecycle-manager.ts:1705]: Fixed in a0aab2bc — dedup flag is now only set when `result.action !== "escalated"`. Escalation hands off to the human, so the flag must not suppress future agent dispatches if the condition recurs after the tracker resets.

File: packages/core/src/lifecycle-manager.ts (hunk 5 above)
Comment (iamasx) [reply packages/core/src/lifecycle-manager.ts]: Fixed in a0aab2bc — merge-conflict tracker is now cleared when conflicts resolve (`hasConflicts` goes false). Each resolution creates an incident boundary so future conflicts start with a fresh escalation budget. Added test `merge conflict tracker resets on resolve — recurrence gets fresh budget` to verify.

File: packages/core/src/lifecycle-manager.ts (hunk 6 above)
Comment (iamasx) [reply packages/core/src/lifecycle-manager.ts]: Fixed in a0aab2bc — enrichedConfig now defaults priority to `"warning"` via `reactionConfig.priority ?? "warning"`, preserving the old direct-dispatch behavior. Added test `merge-conflict notify action preserves warning priority` that routes `info` to empty and `warning` to desktop, verifying the notifier fires at `"warning"`.

File: packages/core/src/lifecycle-manager.ts (hunk 7 above)
Comment (iamasx) [reply packages/core/src/lifecycle-manager.ts:1942]: Fixed in a0aab2bc — `executeReaction` now clears the tracker after a successful escalation (`reactionTrackers.delete(trackerKey)`). This means any future CI failure starts a fresh incident with a fresh budget. Added test `CI escalation clears tracker — next CI failure gets fresh budget` that verifies: escalate → CI passes → CI fails again → sends to agent (fresh attempt 1).

File: packages/core/src/lifecycle-manager.ts [hunk 8]
```diff
@@ -1196,6 +1204,12 @@ export function createLifecycleManager(deps: LifecycleManagerDeps): LifecycleMan
         data: { reactionKey, attempts: tracker.attempts },
       });
       await notifyHuman(event, reactionConfig.priority ?? "urgent");
+
+      // Clear the tracker so future incidents get a fresh budget.
+      // Without this, long-lived sessions that escalated once would
+      // immediately escalate on every future occurrence of the condition.
+      reactionTrackers.delete(trackerKey);
```
Comment (illegalcall) [inline packages/core/src/lifecycle-manager.ts]: ## Residual unbounded-dispatch behavior — escalation reset reopens the spam loop

The persistent-key gate correctly preserves the tracker across `ci_failed → pr_open → ci_failed` flicker. But this `reactionTrackers.delete(trackerKey)` treats escalation as "incident over, fresh budget for next time." In a continuously-failing CI scenario, the *next next-time* is the very next status oscillation — typically ~30 seconds away. The presumption is that the human acts on the escalation page instantly. They don't, on average.

### Trace — 16 push cycles of continuous CI failure, default `retries: 2`

| Push Cycle | Status transition | tracker.attempts | Action |
|---|---|---|---|
| 1 | pr_open → ci_failed | 0 → 1 | msg #1 to agent |
| 2 | pr_open → ci_failed | 1 → 2 | msg #2 to agent |
| 3 | pr_open → ci_failed | 2 → 3 | escalate, **tracker DELETED here** |
| 4 | pr_open → ci_failed | 0 → 1 | msg #3 to agent (fresh tracker) |
| 5 | pr_open → ci_failed | 1 → 2 | msg #4 |
| 6 | pr_open → ci_failed | 2 → 3 | escalate, tracker deleted |
| 7 | pr_open → ci_failed | 0 → 1 | msg #5 |
| ... pattern repeats every 3 cycles ... |

Each push cycle = `failing → pending → failing` round-trip. The pending-out preserves the tracker (correct, your fix). The failing-back re-engages it. After every 3rd entry, escalation deletes the tracker and the loop restarts.

### Tally — what `retries: 2` produces over 16 cycles

| | Original bug | This PR | What `retries:2` should produce |
|---|---|---|---|
| Agent messages | 16 | ~11 | 3 |
| Human escalations | 0 | ~5 | 1 |
| Total notifications | 16 | 16 | 4 |

Agent is spammed at ~67% of original rate. Human is now being paged repeatedly. The total noise is unchanged from the bug — it's just split across two channels.

A user reading `retries: 2` reasonably expects "2 retries, 1 escalation, then *silence on this problem*" — not "2 retries, escalation, fresh budget, repeat indefinitely."

### Why this is the same shape as #1409

The original bug was: tracker cleared too eagerly on every status transition → fresh dispatch every cycle → no escalation. After this fix: tracker cleared on every escalation → fresh dispatch every 3 cycles → escalation fires every 3 cycles. The escalation got bounded; the dispatch rate didn't. Both behaviors are the same root cause: clearing the tracker on a signal that doesn't actually mean "the underlying problem is resolved."

### Recommended fix — Option A: resolution-detected reset

Replace the escalation-clears-tracker rule with a resolution-detected reset. Two parts:

**1. Don't delete the tracker on escalation. Mark it as escalated and short-circuit further dispatches.**

```diff
 interface ReactionTracker {
   attempts: number;
   firstTriggered: Date;
+  escalated?: boolean;
 }

 async function executeReaction(...) {
   // ... existing tracker get/create ...
+
+  // Already escalated — wait for resolution-detected reset before resuming.
+  if (tracker.escalated) {
+    return { reactionType: reactionKey, success: true, action: "escalated", escalated: true };
+  }
+
   tracker.attempts++;
   // ... existing escalation check ...

   if (shouldEscalate) {
     await notifyHuman(event, reactionConfig.priority ?? "urgent");
-
-    // Clear the tracker so future incidents get a fresh budget.
-    reactionTrackers.delete(trackerKey);
-
+    tracker.escalated = true;  // mark, don't delete
     return { ..., action: "escalated", escalated: true };
   }
```

**2. Reset the tracker when the underlying condition is genuinely resolved.** For `ci-failed`, that means CI observed passing for a stable window (filters noise from CI's normal pending↔passing transitions). Add this in `checkSession`, near where `cachedData` is read:

```ts
const CI_PASSING_STABLE_THRESHOLD = 2;

if (cachedData?.ciStatus === "passing") {
  const stableCount = Number(session.metadata["ciPassingStableCount"] ?? "0") + 1;
  if (stableCount >= CI_PASSING_STABLE_THRESHOLD) {
    clearReactionTracker(session.id, "ci-failed");
    updateSessionMetadata(session, { ciPassingStableCount: "" });
  } else {
    updateSessionMetadata(session, { ciPassingStableCount: String(stableCount) });
  }
} else if (session.metadata["ciPassingStableCount"]) {
  // CI flickered out of passing — reset the stability counter
  updateSessionMetadata(session, { ciPassingStableCount: "" });
}
```

### Resulting bounded behavior

Same 16-cycle continuous-failure scenario, default `retries: 2`:

| Push Cycle | tracker state | Action |
|---|---|---|
| 1 | attempts=1 | msg #1 |
| 2 | attempts=2 | msg #2 |
| 3 | attempts=3, escalated=true | escalate (single human page) |
| 4–16 | escalated=true | early-return, no dispatch, no re-escalation |

Final tally: **2 messages, 1 escalation, 13 silent cycles.** Matches the user's mental model of `retries: 2`.

When CI eventually passes (agent fixes it, or human intervenes and fixes it), the resolution-detected reset clears the tracker after 2 stable passing polls. A future genuine CI failure starts fresh.

### Test coverage to add

The current test `"CI escalation clears tracker — next CI failure gets fresh budget"` (lines 2900-ish) explicitly asserts the buggy behavior I'm flagging. It should become `"CI escalation marks tracker as escalated; no further dispatches until CI passes"` and assert the bounded behavior above.

Also add: `"CI passing for stable window resets tracker — subsequent failure starts fresh"`.

### Why this should land before merge

The current behavior dampens the original #1409 symptom to ~67% of its noise floor — better than infinite, but not bounded. Without Option A, users with default `retries: 2` configs will see the symptom recur in any session with sustained CI breakage, just split across agent and human channels. This is the same class of complaint as the original Discord report ("16+ repeated messages"), at a lower rate plus pages.

Fix is small (~20 lines + 2 tests). Worth landing here vs. as a follow-up because shipping the partial fix now means the next user complaint will reopen the same issue.

**Review by illegalcall — CHANGES_REQUESTED** [review]
Follow-up after re-tracing the merged behavior more carefully. The four issues from my previous review are correctly addressed in `a0aab2bc` — thank you for the quick turnaround.

But on a deeper trace I caught a residual issue I underplayed in the first review: the persistent-key gate fixes the original transition-wipe mechanism, but `reactionTrackers.delete(trackerKey)` inside `executeReaction`'s escalate branch (line 1211) introduces a *parallel* mechanism that produces the same observable symptom — sustained dispatches against a sustained problem — at ~67% of the original rate. Inline comment on line 1211 with the trace, the math, and a recommended fix.

**Review by iamasx — COMMENTED** [review]
Option A implemented in d3e5fbe6.

**What changed:**

1. `ReactionTracker` gets `escalated?: boolean`
2. `executeReaction` short-circuits immediately if `tracker.escalated` — no counter increment, no dispatch, no re-escalation notification
3. `reactionTrackers.delete(trackerKey)` on escalation → replaced with `tracker.escalated = true`
4. CI resolution reset in `checkSession`: `ciPassingStableCount` metadata tracks consecutive passing polls. When `ciStatus !== "failing"` for `CI_PASSING_STABLE_THRESHOLD = 2` consecutive polls, `clearReactionTracker("ci-failed")` fires. Counter resets if CI flickers back to failing before threshold.

**Resulting behavior (retries: 2, sustained failure):**

| Cycle | Action |
|-------|--------|
| 1 | attempt 1 → msg to agent |
| 2 | attempt 2 → msg to agent |
| 3 | attempt 3 > retries → escalate, `tracker.escalated = true` |
| 4–N | short-circuit: no dispatch, no re-escalation |
| CI passes 2× stable | `clearReactionTracker` → fresh budget |
| next CI failure | attempt 1 → msg to agent |

**Test changes:**

- `"CI escalation clears tracker — next CI failure gets fresh budget"` → renamed `"CI escalation silences further dispatches — clears only after stable CI pass"`. Now asserts: escalation, then short-circuit on next oscillation, then 2-poll stable pass, then fresh budget.
- Added `"single passing poll does not reset escalated ci-failed tracker"`: verifies the threshold (1 poll is not enough, next failure after 1 poll still short-circuits).

All 920 tests pass. `tsc --noEmit` clean.

File: packages/core/src/lifecycle-manager.ts [hunk 9]
```diff
@@ -1845,6 +1880,27 @@ export function createLifecycleManager(deps: LifecycleManagerDeps): LifecycleMan
...
     }
 
+    // CI resolution tracking — reset the ci-failed tracker (including its escalated
+    // flag) once CI has been passing for CI_PASSING_STABLE_THRESHOLD consecutive polls.
+    // This lets the next real CI failure start with a fresh budget.
+    if (session.pr) {
+      const prKey = `${session.pr.owner}/${session.pr.repo}#${session.pr.number}`;
+      const cachedData = prEnrichmentCache.get(prKey);
+      if (cachedData) {
+        if (cachedData.ciStatus !== "failing") {
```
Comment (illegalcall) [inline packages/core/src/lifecycle-manager.ts]: ## Bug — `pending` blows through the stable-passing threshold

`cachedData.ciStatus !== "failing"` is true for **three** values: `"passing"`, `"pending"`, and `"none"`. The stable-pass logic was meant to detect *resolution*, but it counts any non-failing observation as evidence of resolution — including `pending`, which is the exact value emitted while CI is *still running* on a fresh push.

### Trace — same `retries: 2` scenario, real CI cycle

After a push, GitHub's `statusCheckRollup.state` goes through `PENDING` / `IN_PROGRESS` for the duration of the CI run. `parseCIState()` (in scm-github) maps these to `"pending"`. With 5s polling and a 5-minute CI run, that's ~60 consecutive `pending` polls.

| Poll | ciStatus | stableCount | tracker.attempts | Action |
|---|---|---|---|---|
| 1 | failing | reset to "" | 0 → 1 | msg #1 to agent |
| 2 | pending (push triggered CI) | 0 → 1 | 1 (preserved) | — |
| 3 | pending (CI running) | 1 → 2 | **tracker DELETED here** | — |
| 4 | pending | 1 → 2 | (none, no-op clear) | — |
| ... (CI continues running) ... | | | | |
| 60 | failing (CI completed failing) | reset to "" | 0 → 1 (fresh tracker) | **msg #2 to agent** |
| 61 | pending (next push) | 0 → 1 | 1 | — |
| 62 | pending | 1 → 2 | tracker deleted | — |
| ... |
| 119 | failing | reset to "" | 0 → 1 (fresh) | **msg #3 to agent** |

**The retry budget never accumulates past 1.** Two consecutive pending polls (10s of CI runtime) is plenty to wipe the tracker between failures. The result is exactly the original #1409 spam pattern, just gated by CI run duration instead of poll cadence.

### Why the tests don't catch this

All new tests use `mockBatchEnrichment({ ciStatus: "passing" })` to simulate the off-state. They jump directly from `"failing"` → `"passing"` → `"failing"` with no `"pending"` in between. Real GitHub never produces that sequence — every transition out of `failing` goes through `pending` first while the new check-run starts.

### Fix — one token

```diff
-if (cachedData.ciStatus !== "failing") {
+if (cachedData.ciStatus === "passing") {
```

And update the `else if` branch's intent — the counter should reset on anything that isn't `"passing"` (failing OR pending OR none), since only `"passing"` is positive evidence of resolution:

```diff
-} else if (session.metadata["ciPassingStableCount"]) {
+} else if (cachedData.ciStatus !== "passing" && session.metadata["ciPassingStableCount"]) {
   updateSessionMetadata(session, { ciPassingStableCount: "" });
 }
```

(The condition at the `else if` is already `cachedData.ciStatus === "failing"` from the outer `if (cachedData.ciStatus !== "failing")`. After the fix, the outer condition is `=== "passing"`, so the else branch fires for failing/pending/none — correct: any of those should reset the stability counter.)

The semantic is: *only `passing` counts as positive resolution evidence; everything else (including pending) resets the stability window.*

### Add this regression test

The critical missing case — `failing → pending → pending → failing` should NOT clear the tracker:

```ts
it("pending CI does not count toward ci-failed tracker resolution", async () => {
  // Regression: real CI goes failing → pending (push triggers run) → failing
  // (CI completes failing). Pending must NOT count as resolution, otherwise
  // the tracker resets between every push cycle and we're back at #1409.
  config.reactions = {
    "ci-failed": { auto: true, action: "send-to-agent", message: "...", retries: 2 },
  };

  const lm = setupCheck("app-1", { session: makeSession({ status: "pr_open", pr: makePR() }), registry });

  // Cycle 1: failing → tracker.attempts = 1, msg #1
  await lm.check("app-1");
  expect(mockSessionManager.send).toHaveBeenCalledTimes(1);
  vi.mocked(mockSessionManager.send).mockClear();

  // Cycle 2-3: pending (CI running after agent push) — must NOT reset tracker
  vi.mocked(mockSCM.enrichSessionsPRBatch!).mockImplementation(
    mockBatchEnrichment({ ciStatus: "pending" }),
  );
  await lm.check("app-1");
  await lm.check("app-1");

  // Cycle 4: failing again (CI completed failing)
  vi.mocked(mockSCM.enrichSessionsPRBatch!).mockImplementation(
    mockBatchEnrichment({ ciStatus: "failing" }),
  );
  await lm.check("app-1");

  // Tracker must have continued from attempts=1, now attempts=2 — still under retries:2.
  // If pending wrongly cleared the tracker, this would be attempts=1 again (fresh).
  expect(mockSessionManager.send).toHaveBeenCalledTimes(1); // msg #2, not msg #1 fresh
});
```

And a complementary one: `failing → pending (many) → passing (2) → failing` SHOULD clear (only the passing window resolves the incident).

### Why I'd block on this

The whole point of Option A was bounding agent dispatches per real-world CI failure incident. With the current implementation, that bound only applies under synthetic test conditions. In production, every push cycle resets the tracker because GitHub emits `pending` during CI runs.

Fix is one token. Test is ~30 lines. Worth landing in this PR rather than as a follow-up — otherwise the PR ships without actually solving the bug it's meant to solve.

**Review by illegalcall — CHANGES_REQUESTED** [review]
Thanks for the quick turnaround on Option A — the `escalated` flag and the resolution-detected reset are exactly the right shape. **But the resolution check has a one-token bug at line 1890 that re-introduces the original #1409 spam in production.** All 105 tests pass because none of them mock `ciStatus: "pending"` — which is exactly the value real CI runs produce.

**Review by iamasx — COMMENTED** [review]
Fixed in `3b7a07d0`.

The bug: `cachedData.ciStatus !== "failing"` also matched `"pending"` — the value real GitHub CI emits while a check-run is in progress after a push. Two consecutive pending polls (10s) would wipe the tracker between failures, giving each failure cycle a fresh budget. Exactly #1409 reproduced in production despite the fix.

**One-token change:**
```diff
-if (cachedData.ciStatus !== "failing") {
+if (cachedData.ciStatus === "passing") {
```

The `else if` resets `ciPassingStableCount` for anything that isn't passing (failing, pending, none). Only observed `"passing"` advances the stable window.

**Regression tests added:**
- `"pending CI does not count toward ci-failed tracker resolution"` — failing → pending × 2 → failing: tracker accumulates to attempt 2, not reset. Subsequent pending → failing reaches attempt 3 > retries:2, escalates instead of sending.
- `"only passing CI resets ci-failed tracker — pending mid-run does not interfere"` — escalated tracker, then pending × 3 (stableCount never increments), then passing × 2 (stableCount reaches threshold, clear), then next failure gets fresh budget at attempt 1.

All 922 tests pass. `tsc --noEmit` clean.

**Review by illegalcall — APPROVED** [review]
Verified the fix end-to-end. The pending-bug regression is resolved at line 1890 (`!== "failing"` → `=== "passing"`), and the two new tests at lines 3062+ cover both directions:

- `failing → 2× pending → failing` produces `attempt 2`, not a fresh `attempt 1` (regression for the previous review round).
- `failing → escalated → many× pending → 2× passing → failing` clears the tracker and gives the next incident a fresh budget.

107/107 tests pass on `3b7a07d0`. The original #1409 spam is bounded, the residual escalation-resets bug is bounded, the pending-blowthrough bug is bounded. Three rounds of correct fixes — thanks for the iteration discipline.

## Non-blocking follow-ups worth filing as separate issues

Not blockers for this PR, but worth tracking so they don't get lost:

1. **In-memory `escalated` flag is lost on AO restart.** If AO crashes/restarts mid-incident in the escalated state, the next failing observation creates a fresh tracker. Limited blast radius (only fires on restart during an active escalated incident), but a real hole. Fix: persist the escalated state to session metadata, similar to `lastMergeConflictDispatched`.

2. **The `ciPassingStableCount` mechanism doesn't generalize.** Each new oscillating reaction (`agent-stuck`, `quota-exhausted`, future ones) will need its own equivalent counter, escalated flag, and reset logic. The architectural redesign — Incident as a first-class entity with persisted state and a uniform state machine — would dissolve this whole pattern. Worth filing as a tech-debt issue.

3. **Minor disk-write churn.** The `ciPassingStableCount` reset path runs every poll regardless of whether a tracker exists. For sessions in long-running mergeable status, this writes session metadata each poll. Easy to gate on `reactionTrackers.has()` if it shows up in profiling.

None of these block this merge. Ship it.
